namespace OverLoad.Application.Libreria;

/// <summary>
/// Catálogo de ejercicios de la librería (datos del dominio). Provee, por grupo
/// muscular, la ficha descriptiva de cada ejercicio. No depende de infraestructura.
/// </summary>
public class CatalogoEjercicios
{
    public IReadOnlyList<GrupoEjercicios> ObtenerGrupos() => Grupos;

    private static readonly IReadOnlyList<GrupoEjercicios> Grupos =
    [
        new GrupoEjercicios("Pecho",
        [
            new EjercicioInfo("press-banca-plano", "Press de banca plano", "Pecho",
                "Acostado en el banco, baja la barra controlada hasta el medio del pecho y empuja hasta extender los codos sin bloquearlos de golpe. Mantén los omóplatos retraídos y los pies firmes en el suelo.",
                "Tensión y estiramiento en todo el pectoral, con apoyo de tríceps y hombro frontal. No deberías sentir dolor en el hombro: si es así, baja la barra un poco más abajo y mete los codos.",
                "Trabaja en 6-12 repeticiones. Cuida que la barra baje a la línea de los pezones y no al cuello. Usa un observador o topes de seguridad al ir pesado.",
                "Cinturón en cargas máximas; usa siempre seguros del rack o un compañero. Straps no son necesarios."),
            new EjercicioInfo("press-banca-inclinado", "Press de banca inclinado", "Pecho",
                "Con el banco a 30-45 grados, baja la barra o mancuernas hacia la parte alta del pecho y empuja hacia arriba siguiendo una ligera diagonal.",
                "Énfasis en la porción superior (clavicular) del pectoral y el hombro frontal.",
                "No subas demasiado la inclinación o el hombro tomará el trabajo. 8-12 repeticiones funcionan bien aquí.",
                "Opcional cinturón en pesado; sin straps."),
            new EjercicioInfo("press-banca-declinado", "Press de banca declinado", "Pecho",
                "Con el banco declinado y las piernas sujetas, baja la barra a la parte baja del pecho y empuja hacia arriba.",
                "Mayor activación de la porción inferior del pectoral; suele permitir más carga.",
                "Pide ayuda para entrar y salir de la barra por la posición invertida. 8-12 repeticiones.",
                "Observador recomendado por la posición; cinturón opcional."),
            new EjercicioInfo("flexiones-pecho", "Flexiones de pecho (Push-ups)", "Pecho",
                "En plancha con manos algo más anchas que los hombros, baja el cuerpo en bloque hasta casi tocar el suelo y empuja hacia arriba. Mantén el abdomen y glúteos apretados.",
                "Pecho, tríceps y hombro frontal, con el core estabilizando. La cadera no debe hundirse.",
                "Si es fácil, eleva los pies; si es difícil, apoya las rodillas. Busca rango completo antes que velocidad.",
                "Ninguno necesario (peso corporal)."),
            new EjercicioInfo("aperturas-mancuernas", "Aperturas con mancuernas", "Pecho",
                "Acostado, con codos ligeramente flexionados y fijos, abre los brazos en arco hasta sentir estiramiento y vuelve juntando las mancuernas arriba.",
                "Estiramiento marcado en el pectoral, casi nada de tríceps. Es un ejercicio de aislamiento.",
                "Usa peso moderado y no bajes en exceso para proteger el hombro. 10-15 repeticiones con tempo controlado.",
                "Ninguno; prioriza control sobre carga."),
            new EjercicioInfo("cruces-polea-alta", "Cruces en polea alta", "Pecho",
                "De pie entre dos poleas altas, con leve inclinación al frente, junta las manos al frente y abajo describiendo un arco, y regresa controlado.",
                "Contracción del pecho, sobre todo la porción inferior y media. Tensión constante por la polea.",
                "Aprieta un segundo al juntar las manos. 12-15 repeticiones; ideal para terminar el pecho.",
                "Ninguno necesario."),
            new EjercicioInfo("cruces-polea-baja", "Cruces en polea baja", "Pecho",
                "Desde poleas bajas, lleva las manos hacia arriba y al centro describiendo un arco ascendente, y baja controlado.",
                "Énfasis en la parte superior del pectoral.",
                "Movimiento de aislamiento: peso ligero-moderado, 12-15 repeticiones con buena contracción.",
                "Ninguno necesario."),
            new EjercicioInfo("fondos-paralelas", "Fondos en paralelas (Dips)", "Pecho",
                "Sujeto en las barras paralelas, inclina el torso al frente y baja flexionando los codos hasta sentir estiramiento en el pecho, luego empuja hacia arriba.",
                "Pecho inferior y tríceps. Inclinarse al frente enfatiza pecho; vertical enfatiza tríceps.",
                "No bajes más allá de tu movilidad de hombro. Cuando sea fácil, añade lastre. 6-12 repeticiones.",
                "Cinturón de lastre para añadir peso; sin straps."),
            new EjercicioInfo("pullover-mancuerna", "Pullover con mancuerna", "Pecho",
                "Acostado, sujeta una mancuerna sobre el pecho con ambas manos y llévala por detrás de la cabeza en arco, luego regresa.",
                "Estiramiento amplio del pectoral y serrato; también involucra el dorsal.",
                "Mantén una ligera flexión de codos constante. Peso moderado, 10-15 repeticiones.",
                "Ninguno; cuida el hombro en el estiramiento."),
            new EjercicioInfo("press-maquina-convergente", "Press en máquina convergente", "Pecho",
                "Sentado con la espalda apoyada, empuja las agarraderas al frente juntando ligeramente la trayectoria, y regresa controlado.",
                "Pecho con trayectoria guiada y segura; menos exigencia de estabilización.",
                "Excelente para principiantes o para fallar con seguridad al final de la sesión. 10-15 repeticiones.",
                "Ninguno necesario."),
        ]),

        new GrupoEjercicios("Espalda",
        [
            new EjercicioInfo("dominadas", "Dominadas (Pull-ups)", "Espalda",
                "Colgado de la barra con agarre prono más ancho que los hombros, tira llevando el pecho hacia la barra y baja controlado hasta extender los brazos.",
                "Trabajo intenso del dorsal ancho y la espalda alta; el bíceps asiste. Debes sentir que tiras con la espalda, no solo con los brazos.",
                "Inicia deprimiendo los hombros (lleva los omóplatos abajo). Usa banda elástica o asistencia si aún no salen. 5-10 repeticiones.",
                "Straps si el agarre falla antes que la espalda; cinturón de lastre para añadir peso."),
            new EjercicioInfo("dominadas-supinas", "Dominadas supinas (Chin-ups)", "Espalda",
                "Igual que la dominada pero con agarre supino (palmas hacia ti) al ancho de hombros.",
                "Mayor participación del bíceps junto con el dorsal; suelen ser más fáciles que las pronas.",
                "Buena variante para progresar hacia las dominadas. Rango completo, sin balanceo. 6-10 repeticiones.",
                "Straps opcionales; lastre con cinturón para sobrecargar."),
            new EjercicioInfo("remo-barra", "Remo con barra pesado", "Espalda",
                "Con la cadera bisagrada y el torso casi paralelo al suelo, tira de la barra hacia el abdomen bajo llevando los codos atrás, y baja controlado.",
                "Espalda media y dorsal, con lumbares y femorales sosteniendo la postura. La zona baja no debe redondearse.",
                "Mantén la espalda neutra y el core firme. 6-12 repeticiones. No uses impulso excesivo de cadera.",
                "Cinturón en cargas altas y straps para sostener el agarre en series pesadas."),
            new EjercicioInfo("remo-punta", "Remo en punta (T-Bar Row)", "Espalda",
                "De pie sobre la máquina o barra en landmine, inclinado al frente con espalda neutra, tira del agarre hacia el pecho/abdomen y baja controlado.",
                "Espalda media y dorsal, con mucha tensión en el centro de la espalda.",
                "Permite cargar fuerte con menor estrés lumbar que el remo libre. 8-12 repeticiones.",
                "Straps útiles; cinturón opcional en pesado."),
            new EjercicioInfo("jalon-pecho-amplio", "Jalón al pecho agarre amplio", "Espalda",
                "Sentado con los muslos fijos, agarra la barra ancha y tira hacia la parte alta del pecho llevando los codos abajo y atrás; regresa controlado.",
                "Apertura y trabajo del dorsal ancho, dando amplitud a la espalda. Evita irte muy atrás con el torso.",
                "Baja primero los hombros y luego tira. No jales detrás de la nuca. 10-15 repeticiones.",
                "Straps opcionales si el antebrazo se cansa antes."),
            new EjercicioInfo("jalon-pecho-cerrado", "Jalón al pecho agarre cerrado", "Espalda",
                "Con un agarre estrecho (triángulo o neutro), tira hacia el pecho manteniendo el torso erguido.",
                "Mayor énfasis en el grosor del dorsal y la espalda baja-media; más rango de bíceps.",
                "Buen complemento del agarre amplio. Aprieta al final del tirón. 10-15 repeticiones.",
                "Straps opcionales."),
            new EjercicioInfo("remo-mancuerna-una-mano", "Remo con mancuerna a una mano", "Espalda",
                "Con una rodilla y mano apoyadas en el banco, tira de la mancuerna hacia la cadera llevando el codo atrás, y baja con estiramiento.",
                "Dorsal y espalda media de un lado; permite gran rango y corregir desequilibrios.",
                "No rotes el torso para subir más peso. Estira abajo y aprieta arriba. 8-12 por lado.",
                "Straps opcionales en pesado; banco como apoyo."),
            new EjercicioInfo("pullover-polea-alta", "Pullover en polea alta", "Espalda",
                "De pie frente a la polea alta con brazos casi rectos, tira de la barra hacia los muslos en arco usando el dorsal, y regresa controlado.",
                "Aislamiento del dorsal ancho con tensión constante; casi nada de bíceps.",
                "Mantén los codos ligeramente fijos. Peso moderado, 12-15 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("peso-muerto", "Peso muerto tradicional", "Espalda",
                "Con la barra sobre el medio del pie, bisagra la cadera, agarra y levanta empujando el suelo y extendiendo cadera y rodillas a la vez, manteniendo la espalda neutra. Baja controlado.",
                "Cadena posterior completa: glúteo, femoral, espalda baja y dorsal; el core trabaja fuerte. Nunca debes sentir la espalda baja redondeada bajo carga.",
                "La barra pegada al cuerpo, espalda neutra todo el recorrido. Es muy técnico: domina la forma antes de cargar. 3-6 repeticiones en fuerza.",
                "Cinturón muy recomendado en pesado y straps o agarre mixto para sostener la barra."),
            new EjercicioInfo("hiperextensiones-lumbares", "Hiperextensiones lumbares", "Espalda",
                "En el banco de hiperextensiones, baja el torso bisagrando la cadera y sube hasta alinear el cuerpo, sin hiperextender la espalda.",
                "Espalda baja, glúteo y femoral. Sensación de fortalecimiento lumbar, sin pinzamiento.",
                "Sube hasta la línea del cuerpo, no más. Puedes sostener un disco para progresar. 12-15 repeticiones.",
                "Disco para añadir carga; ningún otro equipo."),
        ]),

        new GrupoEjercicios("Piernas",
        [
            new EjercicioInfo("sentadilla-libre", "Sentadilla libre con barra", "Piernas",
                "Con la barra sobre la espalda alta, baja flexionando cadera y rodillas hasta que los muslos pasen la paralela, manteniendo el pecho arriba y la espalda neutra; sube empujando el suelo.",
                "Cuádriceps, glúteo y aductores, con el core estabilizando. Las rodillas siguen la dirección de los pies sin colapsar hacia dentro.",
                "Mantén el peso en todo el pie y la profundidad que tu movilidad permita. Muy técnica: progresa la carga poco a poco. 5-10 repeticiones.",
                "Cinturón en cargas altas; seguros del rack siempre."),
            new EjercicioInfo("sentadilla-frontal", "Sentadilla frontal", "Piernas",
                "Con la barra apoyada al frente sobre los deltoides y codos altos, baja manteniendo el torso muy vertical y sube.",
                "Énfasis en cuádriceps y mucha demanda de core y espalda alta por la posición vertical.",
                "Codos arriba todo el tiempo para no perder la barra. Usa menos peso que en la sentadilla trasera. 5-10 repeticiones.",
                "Cinturón opcional; seguros del rack."),
            new EjercicioInfo("sentadilla-bulgara", "Sentadilla Búlgara", "Piernas",
                "Con un pie atrás apoyado en un banco, baja el cuerpo flexionando la pierna delantera hasta que el muslo quede paralelo, y sube.",
                "Trabajo unilateral intenso de cuádriceps y glúteo; reta mucho el equilibrio.",
                "Inclina ligeramente el torso para más glúteo o mantente vertical para más cuádriceps. 8-12 por pierna.",
                "Mancuernas para añadir carga; sin más equipo."),
            new EjercicioInfo("prensa-piernas", "Prensa de piernas (Leg Press)", "Piernas",
                "Sentado en la máquina, baja la plataforma flexionando las rodillas hacia el pecho sin despegar la cadera del asiento, y empuja sin bloquear de golpe.",
                "Cuádriceps y glúteo con trayectoria guiada y poco estrés en la espalda.",
                "No bajes tanto que la cadera se enrolle (riesgo lumbar). Pies más altos = más glúteo/femoral. 10-15 repeticiones.",
                "Ninguno necesario; usa los seguros de la máquina."),
            new EjercicioInfo("peso-muerto-rumano", "Peso muerto rumano (RDL)", "Piernas",
                "Con piernas casi rectas, bisagra la cadera llevando la barra cerca de las piernas hasta sentir estiramiento en el femoral, y sube extendiendo la cadera.",
                "Estiramiento y tensión fuerte en femorales y glúteo. La espalda baja se mantiene neutra, no debe doler.",
                "El movimiento es de cadera atrás, no de sentadilla. Baja hasta donde la espalda siga recta. 8-12 repeticiones.",
                "Straps para el agarre y cinturón en cargas altas."),
            new EjercicioInfo("zancadas", "Zancadas con mancuernas (Lunges)", "Piernas",
                "Da un paso al frente y baja hasta que ambas rodillas formen 90 grados, luego empuja para volver o avanza con la otra pierna.",
                "Cuádriceps y glúteo de forma unilateral, con trabajo de equilibrio.",
                "Tronco erguido y paso suficientemente largo. Controla la bajada sin golpear la rodilla. 10-12 por pierna.",
                "Mancuernas o barra para cargar; sin más equipo."),
            new EjercicioInfo("hip-thrust", "Hip Thrust con barra", "Piernas",
                "Con la espalda alta apoyada en un banco y la barra sobre la cadera, empuja la cadera hacia arriba hasta alinear el tronco, apretando el glúteo, y baja controlado.",
                "Máxima activación del glúteo. Arriba debes sentir el glúteo apretado, no la espalda baja.",
                "No hiperextiendas la espalda en el punto alto; mete la pelvis. Usa una almohadilla en la barra. 8-15 repeticiones.",
                "Almohadilla para la barra; cinturón opcional en pesado."),
            new EjercicioInfo("extensiones-cuadriceps", "Extensiones de cuádriceps", "Piernas",
                "Sentado en la máquina, extiende las rodillas levantando el rodillo hasta casi bloquear, aprieta y baja controlado.",
                "Aislamiento puro del cuádriceps, con pico de contracción arriba.",
                "Evita el balanceo. Aprieta un segundo arriba. Ideal para pre-fatiga o remate. 12-15 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("curl-isquios", "Curl de isquios (Acostado o Sentado)", "Piernas",
                "En la máquina, flexiona las rodillas llevando el rodillo hacia los glúteos y baja controlado.",
                "Aislamiento del femoral (isquiotibiales), con buena contracción.",
                "No despegues la cadera de la máquina. Controla la fase de bajada. 10-15 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("elevacion-talones", "Elevación de talones (Pantorrillas)", "Piernas",
                "De pie o sentado, eleva los talones lo más alto posible apretando el gemelo y baja con estiramiento completo.",
                "Contracción y estiramiento del gemelo y sóleo. Trabaja todo el rango.",
                "Haz pausa arriba y abajo; nada de rebotes rápidos. 12-20 repeticiones por su rapidez de recuperación.",
                "Ninguno; máquina o mancuerna para cargar."),
        ]),

        new GrupoEjercicios("Hombros",
        [
            new EjercicioInfo("press-militar", "Press militar con barra", "Hombros",
                "De pie con el core apretado, empuja la barra desde los hombros hasta arriba de la cabeza extendiendo los codos, y baja controlado a la clavícula.",
                "Hombro frontal y lateral, con tríceps asistiendo y el core estabilizando. No arquees mucho la espalda baja.",
                "Aprieta glúteo y abdomen para no compensar con la espalda. 5-10 repeticiones.",
                "Cinturón en cargas altas; sin straps."),
            new EjercicioInfo("press-arnold", "Press Arnold con mancuernas", "Hombros",
                "Sentado, parte con las palmas hacia ti a la altura del cuello y empuja girando las muñecas hasta terminar con las palmas al frente arriba.",
                "Recorre el hombro frontal y lateral gracias a la rotación; sensación de trabajo completo del deltoides.",
                "Hazlo fluido y sin peso excesivo por la rotación. 8-12 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("elevaciones-laterales", "Elevaciones laterales", "Hombros",
                "De pie con leve flexión de codos, eleva las mancuernas a los lados hasta la altura de los hombros y baja controlado.",
                "Aislamiento del deltoides lateral, que da anchura al hombro. Debes sentirlo en el costado del hombro, no en el cuello.",
                "Peso ligero y nada de impulso; lidera con los codos. 12-20 repeticiones.",
                "Ninguno; la técnica manda sobre el peso."),
            new EjercicioInfo("elevaciones-frontales", "Elevaciones frontales", "Hombros",
                "Eleva la mancuerna o disco al frente hasta la altura de los ojos con el brazo casi recto, y baja controlado.",
                "Aislamiento del deltoides frontal.",
                "No te balancees. Alterna brazos si te ayuda a controlar. 12-15 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("pajaros", "Pájaros (Rear delt fly)", "Hombros",
                "Inclinado al frente con el torso casi paralelo, abre los brazos a los lados con codos algo flexionados y baja controlado.",
                "Deltoides posterior y espalda alta. Sensación en la parte trasera del hombro.",
                "Peso muy ligero, sin usar la espalda para impulsar. 15-20 repeticiones.",
                "Ninguno; puede hacerse en pec-deck invertido."),
            new EjercicioInfo("face-pulls", "Face pulls en polea", "Hombros",
                "Desde una polea a la altura de la cara con cuerda, tira hacia la frente separando las manos y llevando los codos altos y atrás.",
                "Deltoides posterior y rotadores externos; ideal para salud del hombro y postura.",
                "Movimiento controlado, aprieta atrás. Excelente como ejercicio correctivo. 15-20 repeticiones.",
                "Cuerda de polea; ningún otro equipo."),
            new EjercicioInfo("remo-al-cuello", "Remo al cuello (Upright row)", "Hombros",
                "Con la barra o mancuernas frente al cuerpo, tira hacia arriba llevando los codos altos hasta la altura del pecho, y baja controlado.",
                "Deltoides lateral y trapecio. Si molesta el hombro, usa agarre más ancho o reduce la altura.",
                "No subas por encima de la clavícula para evitar pinzamiento. 10-15 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("encogimientos-hombros", "Encogimientos de hombros (Shrugs)", "Hombros",
                "Con peso en las manos y brazos rectos, eleva los hombros hacia las orejas, aprieta arriba y baja controlado.",
                "Trapecio superior. Pico de contracción arriba.",
                "No ruedes los hombros; sube y baja recto. Pausa arriba. 12-15 repeticiones.",
                "Straps muy útiles para sostener cargas altas."),
            new EjercicioInfo("press-bradford", "Press Bradford", "Hombros",
                "Pasa la barra de adelante de la cabeza a atrás y de regreso en un movimiento continuo, sin bloquear arriba, manteniendo tensión.",
                "Tensión constante en los deltoides por el rango parcial continuo.",
                "Requiere buena movilidad de hombro; usa poco peso. Mantén el core firme. 10-12 repeticiones.",
                "Ninguno; cuida la movilidad del hombro."),
        ]),

        new GrupoEjercicios("Brazos",
        [
            new EjercicioInfo("curl-biceps-barra-z", "Curl de bíceps con barra Z", "Brazos",
                "De pie con los codos pegados al torso, flexiona los brazos subiendo la barra y baja controlado sin balancear.",
                "Contracción del bíceps; la barra Z reduce la tensión en muñecas.",
                "Codos quietos a los lados; nada de impulso de cadera. 8-12 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("curl-martillo", "Curl martillo con mancuernas", "Brazos",
                "Con agarre neutro (palmas enfrentadas), flexiona los brazos subiendo las mancuernas y baja controlado.",
                "Bíceps y, sobre todo, braquial y braquiorradial (antebrazo), dando grosor al brazo.",
                "Mantén el agarre neutro todo el rango. Puedes alternar brazos. 8-12 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("curl-arana", "Curl araña (Spider curl)", "Brazos",
                "Boca abajo sobre un banco inclinado con los brazos colgando, flexiona subiendo el peso hacia los hombros y baja controlado.",
                "Aislamiento del bíceps con máxima tensión en la fase corta; nada de impulso posible.",
                "Excelente para el pico del bíceps. Peso moderado, 10-15 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("curl-predicador", "Curl predicador en banco", "Brazos",
                "Con los brazos apoyados en el banco predicador, flexiona subiendo el peso y baja controlado sin extender de golpe.",
                "Aislamiento del bíceps, sobre todo en la parte baja del recorrido.",
                "No extiendas bruscamente abajo para cuidar el codo. 8-12 repeticiones.",
                "Ninguno; barra Z o mancuerna."),
            new EjercicioInfo("extensiones-triceps-polea", "Extensiones de tríceps en polea", "Brazos",
                "Frente a la polea alta con cuerda o barra, extiende los codos hacia abajo manteniéndolos pegados al cuerpo, y regresa controlado.",
                "Aislamiento del tríceps con tensión constante. Codos quietos.",
                "Solo se mueve el antebrazo. Abre la cuerda al final para más contracción. 12-15 repeticiones.",
                "Cuerda o barra de polea."),
            new EjercicioInfo("press-frances", "Press francés con barra Z", "Brazos",
                "Acostado, con la barra arriba, flexiona los codos bajando la barra hacia la frente y extiende sin mover los codos.",
                "Estiramiento y trabajo de las tres cabezas del tríceps.",
                "Mantén los codos apuntando arriba y fijos. Controla la bajada. 8-12 repeticiones.",
                "Ninguno; barra Z reduce molestia de muñeca."),
            new EjercicioInfo("rompecraneos", "Rompecráneos (Skullcrushers)", "Brazos",
                "Variante del press francés en la que la barra baja por detrás de la cabeza para mayor estiramiento del tríceps.",
                "Estiramiento profundo de la cabeza larga del tríceps.",
                "Movimiento lento y controlado; nombre intimidante, técnica cuidadosa. 8-12 repeticiones.",
                "Ninguno necesario."),
            new EjercicioInfo("fondos-triceps-banco", "Fondos de tríceps en banco", "Brazos",
                "Con las manos en el borde de un banco y los pies al frente, baja el cuerpo flexionando los codos y empuja hacia arriba.",
                "Tríceps principalmente; el hombro frontal asiste.",
                "No bajes tanto que el hombro se estrese. Estira las piernas o añade disco para progresar. 10-15 repeticiones.",
                "Disco sobre los muslos para añadir carga."),
            new EjercicioInfo("patada-triceps", "Patada de tríceps (Kickbacks)", "Brazos",
                "Inclinado con el brazo pegado al torso, extiende el codo llevando la mancuerna atrás hasta estirar el brazo, y regresa.",
                "Aislamiento del tríceps con pico de contracción al final.",
                "Codo fijo y quieto; solo se mueve el antebrazo. Peso ligero, 12-15 repeticiones.",
                "Ninguno necesario."),
        ]),

        new GrupoEjercicios("Core",
        [
            new EjercicioInfo("plancha", "Plancha isométrica (Plank)", "Core",
                "Apoyado en antebrazos y puntas de los pies, mantén el cuerpo en línea recta apretando abdomen y glúteos sin dejar caer la cadera.",
                "Tensión en todo el abdomen y el core profundo. La espalda baja no debe arquearse ni hundirse.",
                "Calidad sobre tiempo: mantén la línea recta. Empieza con 20-40 segundos y progresa.",
                "Ninguno necesario (isométrico)."),
            new EjercicioInfo("crunches-polea", "Crunches en polea alta", "Core",
                "Arrodillado frente a la polea alta con la cuerda tras la nuca, flexiona el tronco llevando los codos hacia los muslos contrayendo el abdomen.",
                "Contracción fuerte del recto abdominal con carga progresiva.",
                "Redondea la columna al bajar el pecho; no jales con los brazos ni con la cadera. 12-15 repeticiones.",
                "Cuerda de polea."),
            new EjercicioInfo("elevacion-piernas-colgado", "Elevación de piernas colgado", "Core",
                "Colgado de la barra, eleva las piernas (rectas o con rodillas flexionadas) llevándolas al frente con control, y baja sin balancear.",
                "Abdomen, sobre todo la parte baja, y flexores de cadera.",
                "Evita el balanceo; sube llevando la pelvis, no solo las piernas. 8-15 repeticiones.",
                "Straps o ganchos si el agarre se cansa; correas de soporte de codo opcionales."),
            new EjercicioInfo("rueda-abdominal", "Rueda abdominal (Ab wheel)", "Core",
                "De rodillas, rueda la rueda hacia adelante extendiendo el cuerpo lo más posible sin arquear la espalda, y regresa contrayendo el abdomen.",
                "Tensión muy intensa en todo el core anti-extensión. La espalda baja no debe arquearse.",
                "Avanza solo hasta donde puedas mantener el abdomen apretado. Muy exigente: progresa el rango poco a poco.",
                "Rueda abdominal; superficie acolchada para las rodillas."),
            new EjercicioInfo("giros-rusos", "Giros rusos (Russian twist)", "Core",
                "Sentado con el torso inclinado atrás y los pies elevados o apoyados, gira el tronco llevando el peso de un lado a otro.",
                "Oblicuos y core rotacional.",
                "Gira desde el tronco, no solo con los brazos; controla el movimiento. 15-20 toques en total.",
                "Disco, mancuerna o balón medicinal para cargar."),
            new EjercicioInfo("woodchoppers", "Woodchoppers en polea", "Core",
                "Desde una polea alta o baja, lleva el agarre en diagonal cruzando el cuerpo con brazos casi rectos, girando el tronco.",
                "Oblicuos y core rotacional con tensión constante; patrón funcional.",
                "El giro viene del tronco y la cadera, no de los brazos. 12-15 por lado.",
                "Polea con agarre; ningún otro equipo."),
            new EjercicioInfo("dragon-flags", "Dragon flags", "Core",
                "Acostado sujetando un apoyo tras la cabeza, eleva el cuerpo recto desde los hombros y baja en línea recta controlando con el abdomen.",
                "Tensión máxima en todo el recto abdominal; ejercicio avanzado.",
                "Mantén el cuerpo rígido como tabla y baja lento. Domina la plancha y las elevaciones antes. 5-10 repeticiones.",
                "Banco o barra firme donde sujetarse."),
            new EjercicioInfo("toques-talon", "Toques de talón (Heel touches)", "Core",
                "Acostado con las rodillas flexionadas, flexiona el tronco lateralmente tocando cada talón con la mano del mismo lado.",
                "Oblicuos, con sensación de quemazón lateral.",
                "Mantén la zona baja apoyada y mueve solo el tronco. 15-20 por lado.",
                "Ninguno necesario (peso corporal)."),
            new EjercicioInfo("bicicletas-abdominales", "Bicicletas abdominales", "Core",
                "Acostado, lleva codo y rodilla opuestos a encontrarse alternando lados en un pedaleo controlado.",
                "Recto abdominal y oblicuos de forma dinámica.",
                "Hazlo lento y con rango completo, no rápido y corto. La zona baja pegada al suelo. 15-20 por lado.",
                "Ninguno necesario (peso corporal)."),
        ]),
    ];
}
